version: '3.8'

services:
  zabbix-bot:
    build: .
    container_name: zabbix-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GROUP_ID=${GROUP_ID}
      - TOPIC_ID=${TOPIC_ID}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "7000:7000"
    volumes:
      - ./logs:/app/logs  # Прокидываем папку с логами