version: '3.8'

services:
  zabbix-telegram-bot:
    build: .
    container_name: zabbix-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs # Монтируем папку с логами
    network_mode: host # Для доступа к PostgreSQL на localhost
